### ISSUE TITLE
Does this work on osx?

### ISSUE THREAD

**Issue by mrkaspa** [whitequark/ocaml-inotify#12]

**Comment by whitequark** [comment]
From the first line of README:

> This package contains bindings for Linux's filesystem monitoring interface, inotify.

Linux is not OS X.

**Comment by mrkaspa** [comment]
lol sorry

**Comment by dsheets** [comment]
https://github.com/dsheets/ocaml-osx-fsevents offers file system event bindings for OCaml on OS X.
