### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by toots** [whitequark/ocaml-inotify#21]
Hi,

Is there a new release planned? The absence of version fixed in https://github.com/whitequark/ocaml-inotify/pull/20 keeps forcing us to have a special treatment for this package in our CI build pipeline, which causes issues every now and then.

Thanks!

**Comment by whitequark** [comment]
@c-cube ?

**Comment by c-cube** [comment]
Yep, on it!

**Comment by toots** [comment]
Thanks y'all!

**Comment by toots** [comment]
Ping!

**Comment by c-cube** [comment]
Oh, sorry, it has been released. See 2.4.1.
