### ISSUE TITLE
the lwt_inotify library is broken

### ISSUE THREAD

**Issue by ivg** [whitequark/ocaml-inotify#22]
The Lwt_inotify module uses blocking calls from the Inotify module and just returns their results with `Lwt.return`. Therefore, instead of returning promises, all functions in the interface are blocking the execution until the underlying value is ready. This hangs any program that is trying to use Lwt_inotify. Instead, the bindings should use `Lwt_unix` functions to read data from the file descriptor (which will enter unblocking mode and will create promises that will be fulfilled when the data is ready).

As an immediate mitigation, I suggest removing Lwt_unix altogether, as it is confusing people. To fix this issue, it should be rewritten from scratch anyways.

**Comment by whitequark** [comment]
Did you miss https://github.com/whitequark/ocaml-inotify/blob/master/lib/lwt_inotify.ml#L35 and https://github.com/whitequark/ocaml-inotify/blob/master/lib/lwt_inotify.ml#L49 ?

**Comment by ivg** [comment]
I did indeed! Are there any reasons why other functions, like `create` and `add_watch` that do not perform any Lwt IO operations are wrapped into Lwt promises?

**Comment by ivg** [comment]
> I don't think that would achieve anything, since there's no way to poll on completion for those.

No, I mean, it would be much better if they will return immediate results, e.g., that the `create` function will have type `t` instead of `t Lwt.t`. It will be much easier to use this interface.

**Comment by whitequark** [comment]
Oh! I wrote this so long I forgot how it looks like.

That would be a breaking change, no? And it changes how errors are propagated.

**Comment by ivg** [comment]
Well, yes. It's actually a blocker for me. E.g., if I want to set up a watch for some data access object (DAO), which was pure before, e.g., a DAO around a directory, 

```
type t = {root : string}
let create root = {root}
```

Now, if I want to add a watch, I would have to make my `create` constructor impure. This change will break all the code that uses it, as the impure (aka lwt) computation will spread around the code base as cancer. And in many cases it would be just impossible. 


Concerning churn, the change would be like, going from
```
let create () =
  try
    let unix_fd = Inotify.create () in
    return {
      queue   = Queue.create ();
      lwt_fd  = Lwt_unix.of_unix_file_descr unix_fd;
      unix_fd; }
  with exn ->
    Lwt.fail exn
```
to
```
let create' () =
    let unix_fd = Inotify.create () in
    {
      queue   = Queue.create ();
      lwt_fd  = Lwt_unix.of_unix_file_descr unix_fd;
      unix_fd; 
   }
 let create () = try create' () with exn -> Lwt.fail  exn
```
i.e., a one-liner per function (2 lines in total)

**Comment by ivg** [comment]
Awesome! Here we go https://github.com/whitequark/ocaml-inotify/pull/23
