### ISSUE TITLE
exception Unix.Unix_error(Unix.EINVAL, "read", "")

### ISSUE THREAD

**Issue by Ninjapouet** [whitequark/ocaml-inotify#8]
Given when trying the README example on a 3.13.0-24-generic #47-Ubuntu SMP (Mint) 64bits. Seems that the bytes_queued length reading isn't valid anymore since kernel 2.6.21. I don't know why but it expects a buffer of sizeof(struct inotify_event) + NAME_MAX + 1 whatever the real event size is (see inotify man page). I had the same issue with my own bindings using ctypes until i used the size above.

**Comment by whitequark** [comment]
Very interesting. Looks like this is only exhibited on a blocking socket, which is why tests didn't catch it.

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/6760
